### ISSUE TITLE
does not work with 2010-10-07

### ISSUE THREAD

**Issue by tstaerk** [dr4Ke/editsections#1]
this plugin does not work with dokuwiki-2010-10-07.

Reproduce:
1. Install dokuwiki
2. Install editsections plugin
3. create a page
===== 1 =====

hello world
===== 2 =====

hi moon

actual result:
the edit button for the section "1" is on the line of "2".

expected result:
the edit button for the section "1" is on the line of "1".

**Comment by tstaerk** [comment]
this is also valid for version 2009-12-25
=> this was wrong. I applied the patch wrong.

**Comment by dr4Ke** [comment]
This is strange as I'm using this plugin with this dokuwiki version. I'll try with both versions when I have some time.

**Comment by tstaerk** [comment]
maybe you still have the other editsections plugin installed? Please try with a fresh dokuwiki installation. Thanks for your plugin, I use it at work!

**Comment by tstaerk** [comment]
hey, I would like to pay money to get this going again. How much do you want?

**Comment by dr4Ke** [comment]
I don't know how much but it sure will be appreciated. I'll do my best to work on this issue this week.
How much do you think it is worth ?

**Comment by dr4Ke** [comment]
There are some changes in the next release on how are handled section edit buttons.
This plugin can't work in the same way that it was in previous releases. I have to look further in the dokuwiki code to write a new version of this plugin.
Stay tuned.

**Comment by dr4Ke** [comment]
Branch rc2010 contains preliminary works to work with 2010-10-07.
Right now, the plugin works in non nested mode only. The nested mode should not be too hard to do.
The way the plugin works breaks a new feature of dokuwiki : section name in the summary when editing. I'll try to solve this problem but I'm not sure it could be.

**Comment by dr4Ke** [comment]
Now in branch rc2010, the plugins works in nested and flat mode. Sections names are OK too.
Another problem appeared : the edition page no longer contains the toolbar.
I reopened the issue until the changes are merged in the master branch.

**Comment by dr4Ke** [comment]
Oh. The plugin in the rc2010 branch should work with earlier dokuwiki releases (20091225c, at least) as well. I didn't test it, though. I'll have to do it before merging.

**Comment by dr4Ke** [comment]
New release of the plugin is now available in the master branch.

**Comment by tstaerk** [comment]
Testing with dokuwiki-rc2010-10-27:

Works okay one time. Then you click on an edit button, do not change anything and click save. Then, all edit buttons are away. 

But after you changed a page, your edit buttons are shown. Changing triggers a re-parsing. If you do not change a page, it is not parsed, but fetched from cache.

In my opinion your edit buttons do not always appear because you only register against PARSER_HANDLER_DONE which draws when you change a site. You should also act on PARSER_CACHE_USE which draws when you only display a page.

makes sense?

**Comment by dr4Ke** [comment]
I had this issue once. I'm sure this is a cache issue, as you pointed. The thing is it did not happen again.

I'll try with your suggestion.

Thanks for the report.
